apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb 
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: #La de dockerhub
          env:
            - name: MYSQL_DATABASE
              value: "ciber"
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
            - name: db-setup
              mountPath: /docker-entrypoint-initdb.d/setup.sql
              readOnly: true 
      volumes:
        - name: db-data
          emptyDir: {}
        - name: db-setup
          hostPath:
            path: /vagrant/TablasBBDD.sql
            type: File
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config
data:
  PMA_HOST: "mariadb"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          envFrom:
            - configMapRef:
                name: phpmyadmin-config
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DB_PORT: "3306"
  DB_HOST: "db"
  DB_DATABASE: "ciber"
  DB_USERNAME: "user"
  DB_PASSWORD: "userpw"
  SECRET_KEY: "LDR_PEPSaaaaaaasadasqe12312312dcac2334caaaaaaaaaaaaaaaaa"
  WTF_CSRF_SECRET_KEY: "$LDR_PEPSsdasdadsadssd"
  HOST: "0.0.0.0"
  PORT: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: fernando666/pepsapi:1.0
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: api-config